### ISSUE TITLE
closure/templates not found

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/rules_closure#26] opened 2016-03-31 23:22 UTC
Error when using closure_template_js_library. I believe this is due to the same problem as https://github.com/bazelbuild/rules_closure/issues/9 - when I have time, I can provide a way to reproduce.

```
no such package 'closure/templates': BUILD file not found on package path and referenced by '{build target}'.
```

**Comment by jart** [comment] 2016-04-01 01:30
It's almost certainly a duplicate of #9.

**Closed by jart** 2016-04-01 01:30 UTC
Labels: duplicate
