### ISSUE TITLE
Suppress type errors in protobuf_js external dependency

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_closure#168] opened 2016-11-12 12:05 UTC
OK so I'm evaluating the new überstrict rules_closure 64f93d91a11db829d8468e6a476ff047131fb927.  Please advise on how to deal with this one that originates from use of a `closure_js_proto_library`:

```
external/protobuf_js/js/map.js:352: ERROR - Union of function(this:jspb.BinaryReader,V,?):? with function(this:jspb.BinaryWriter,number,V):? would create an impossible type
 *          function(this:jspb.BinaryReader,V,?)} valueWriterFn
            ^
  ProTip: "JSC_NTI_UNION_IS_UNINHABITABLE" or "checkTypes" or "newCheckTypes" or "newCheckTypesClosureClean" or "newCheckTypesExtraChecks" can be added to the `suppress` attribute of:
  @io_bazel_rules_closure//closure/protobuf:jspb
  Alternatively /** @suppress {newCheckTypes} */ can be added to the source file.

external/protobuf_js/js/map.js:448: ERROR - Cannot use ! to restrict type variable type.
Prefer to make type argument non-nullable and add null explicitly where needed (e.g. through ?T or T|null)
 * @param {!K} key The entry's key.
            ^
  ProTip: "JSC_NTI_CANNOT_MAKE_TYPEVAR_NON_NULL" or "checkTypes" or "newCheckTypes" or "newCheckTypesExtraChecks" can be added to the `suppress` attribute of:
  @io_bazel_rules_closure//closure/protobuf:jspb
  Alternatively /** @suppress {newCheckTypes} */ can be added to the source file.

2 error(s), 0 warning(s)
```

**Comment by jart** [comment] 2016-11-12 22:19
This is probably a duplicate of #169 since those errors are probably being triggered when building the closure_js_binary.

**Closed by jart** 2016-11-12 22:19 UTC
Labels: duplicate
