### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#142] opened 2016-09-29 12:37 UTC
Hi,
Just curious about what it would look like to use these rules to build localized client-side soy templates. (Our web app is localized into ~40 languages).
Thank you!
Rob

**Comment by jart** [comment] 2016-10-08 06:34
The Closure Tools have excellent localization support. I just haven't had the time to integrate it seamlessly into this build system. You should be able to work around this by using the `defs` attribute on `closure_js_binary` which is able to turn `goog.getMsg()` function calls into the localized text. Then you can produce a separate JS binary for each language. If the workaround doesn't work, then I'll be happy to modify the code so the workarounds can. But I don't have the cycles right now to provide polished rules for i18n/l10n.

**Comment by jart** [comment] 2016-11-12 06:31
Closing as duplicate of #13.

**Closed by jart** 2016-11-12 06:31 UTC
Labels: duplicate
